const fs = require('fs');
let c = fs.readFileSync('src/routes/public.ts', 'utf8');

// Find the exact player route block
const start = c.indexOf('// ── 玩家档案页（按 ban id 查询）──');
const oldRouteStart = c.indexOf("publicRoutes.get('/player/:id'", start);
const oldRouteEnd = c.indexOf('\n\nfunction statusLabel', oldRouteStart);

if (start === -1 || oldRouteStart === -1 || oldRouteEnd === -1) {
  console.log('ERROR: markers not found');
  process.exit(1);
}

// The new route, carefully written
const newRoute = [
"// ── 玩家/管理员详情页（统一按 Steam64 ID 查询）──",
"",
"publicRoutes.get('/player/:steamId', async (c) => {",
"  const steamId = c.req.param('steamId')",
"",
"  // 占位符 Steam ID 不展示详情页",
"  const isPlaceholder = !steamId || steamId.length < 6 || steamId === 'N/A' || steamId === 'unknown' || steamId === '0'",
"  if (isPlaceholder) {",
"    return c.html(Layout({",
"      title: '玩家档案', currentPath: '/',",
"      children: PlayerProfilePage({",
"        nickname: '—', steam_id: steamId,",
"        totalBans: 0, currentStatus: '', currentStatusLabel: '无记录',",
"        currentStatusColor: 'cyber-badge-neutral', highestLevel: '—', highestLevelColor: '',",
"        onWatchlist: false, watchlistReason: null,",
"        firstBanDate: '—', lastBanDate: '—', maskedIp: null, bans: [],",
"        adminData: null,",
"      }),",
"    }))",
"  }",
"",
"  // 查询管理员身份",
"  const admin = await c.env.DB.prepare(",
"    'SELECT id, steam_id, username, permission_group, game_name, qq_name, position, supervisor FROM admins WHERE steam_id = ? AND is_active = 1'",
"  ).bind(steamId).first<{ id: number; steam_id: string; username: string; permission_group: string; game_name: string; qq_name: string; position: string; supervisor: string }>()",
"",
"  // 查询封禁记录（排除违纪处罚）",
"  const bans = await c.env.DB.prepare(",
"    `SELECT b.*, a.game_name as handled_by_name FROM bans b",
"     LEFT JOIN admins a ON b.handled_by = a.id",
"     WHERE b.steam_id = ? AND b.is_archived = 0 AND b.violation_level != 'admin_discipline'",
"     ORDER BY b.created_at DESC`",
"  ).bind(steamId).all<BanRow & { handled_by_name: string | null }>()",
"",
"  if (bans.results.length === 0 && !admin) {",
"    return c.html(Layout({",
"      title: '玩家档案', currentPath: '/',",
"      children: PlayerProfilePage({",
"        nickname: '—', steam_id: steamId,",
"        totalBans: 0, currentStatus: '', currentStatusLabel: '无记录',",
"        currentStatusColor: 'cyber-badge-neutral', highestLevel: '—', highestLevelColor: '',",
"        onWatchlist: false, watchlistReason: null,",
"        firstBanDate: '—', lastBanDate: '—', maskedIp: null, bans: [],",
"        adminData: null,",
"      }),",
"    }))",
"  }",
"",
"  const watchEntry = await c.env.DB.prepare(",
"    'SELECT reason, notes FROM watchlist WHERE steam_id = ?'",
"  ).bind(steamId).first<{ reason: string; notes: string }>()",
"",
"  const processed = bans.results.map(b => ({ ...b, status: computeStatus(b) }))",
"  const totalBans = processed.length",
"  const currentStatus = processed.length > 0 ? processed[0].status : ''",
"  const currentStatusLabel = processed.length > 0 ? statusLabel(currentStatus) : '无记录'",
"  const currentStatusColor = processed.length > 0 ? statusBadgeColor(currentStatus) : 'cyber-badge-neutral'",
"",
"  const levelOrder: Record<string, number> = { level1: 0, level2: 1, level3: 2, warning: 3 }",
"  const sortedByLevel = [...processed].sort((a, b) =>",
"    (levelOrder[a.violation_level] ?? 99) - (levelOrder[b.violation_level] ?? 99)",
"  )",
"  const highestLevel = sortedByLevel.length > 0 ? sortedByLevel[0].violation_level : '—'",
"  const highestLevelColor = lvStatColor(highestLevel)",
"",
"  const dates = processed.map(b => b.ban_time).filter(Boolean).sort()",
"  const firstBanDate = dates.length > 0 ? fmtDate(dates[0]) : '—'",
"  const lastBanDate = dates.length > 0 ? fmtDate(dates[dates.length - 1]) : '—'",
"",
"  const ip = processed.find(b => b.ip_address)?.ip_address || null",
"  const maskedIp = ip ? ip.replace(/\.\d+$/, '.***') : null",
"",
"  const nickname = processed.length > 0 ? processed[0].nickname : (admin?.game_name || '—')",
"",
"  const onWatchlist = !!watchEntry",
"  const watchlistReason = watchEntry?.reason || null",
"",
"  // 如果是管理员，查询违纪处罚记录",
"  let adminDisciplines: Array<{ban_duration: string; reason: string; ban_time: string; handled_by_name: string | null}> = []",
"  if (admin) {",
"    const discRows = await c.env.DB.prepare(",
"      `SELECT b.ban_duration, b.reason, b.ban_time, a.game_name as handled_by_name FROM bans b",
"       LEFT JOIN admins a ON b.handled_by = a.id",
"       WHERE b.steam_id = ? AND b.violation_level = 'admin_discipline'",
"       ORDER BY b.created_at DESC LIMIT 20`",
"    ).bind(steamId).all()",
"    adminDisciplines = discRows.results as Array<{ban_duration: string; reason: string; ban_time: string; handled_by_name: string | null}>",
"  }",
"",
"  const profileData = {",
"    nickname, steam_id: steamId,",
"    totalBans, currentStatus, currentStatusLabel, currentStatusColor,",
"    highestLevel, highestLevelColor,",
"    onWatchlist, watchlistReason,",
"    firstBanDate, lastBanDate, maskedIp,",
"    bans: processed.map(b => ({",
"      ban_time: b.ban_time, reason: b.reason,",
"      ban_duration: b.ban_duration, violation_level: b.violation_level,",
"      status: b.status, handled_by_name: b.handled_by_name,",
"    })),",
"    adminData: admin ? {",
"      id: admin.id, username: admin.username, gameName: admin.game_name,",
"      permissionGroup: admin.permission_group, position: admin.position,",
"      supervisor: admin.supervisor, qqName: admin.qq_name,",
"      disciplines: adminDisciplines,",
"    } : null,",
"  }",
"",
"  return c.html(Layout({",
"    title: `${nickname} - 玩家档案`,",
"    currentPath: '/',",
"    children: PlayerProfilePage(profileData),",
"  }))",
"})",
].join('\n');

c = c.substring(0, start) + newRoute + c.substring(oldRouteEnd);
fs.writeFileSync('src/routes/public.ts', c);
console.log('Player route replaced successfully');
